name: Call Reusable Docker Workflow

on:
  push:
    branches:
      - develop
      - main

jobs:
  call-workflow:
    uses: pritimane1809/workkflow_repository/.github/workflows/docker-ci.yml@v1.0.0

    with:
      image_name: my-app   # ✅ only plain string or github context
      tag: ${{ github.ref == 'refs/heads/develop' && format('staging-{0}', github.sha) || format('prod-{0}', github.run_number) }}

    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      SLACK_WBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
